WITH OUTS AS (
    SELECT
        ANIMAL_ID
    FROM (
        SELECT ANIMAL_ID
        FROM ANIMAL_INS
        WHERE SEX_UPON_INTAKE LIKE 'Intact%'
    ) i
    JOIN ANIMAL_OUTS o USING (ANIMAL_ID)
    WHERE o.SEX_UPON_OUTCOME LIKE 'Spayed%'
        OR o.SEX_UPON_OUTCOME LIKE 'Neutered%'
)
SELECT
    ao.ANIMAL_ID,
    ao.ANIMAL_TYPE,
    ao.NAME
FROM ANIMAL_OUTS ao
JOIN OUTS o USING (ANIMAL_ID)
ORDER BY ao.ANIMAL_ID;