SELECT
    I.REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    ROUND(SUM(REVIEW_SCORE) / COUNT(*), 2) AS SCORE
FROM REST_INFO I
JOIN REST_REVIEW R
    ON I.REST_ID = R.REST_ID
WHERE
    I.ADDRESS LIKE '서울%'
GROUP BY
    REST_ID
ORDER BY
    SCORE DESC,
    FAVORITES DESC