WITH T1 AS (
    SELECT
        YEAR(SALES_DATE) YEAR,
        MONTH(SALES_DATE) MONTH,
        0 AS GENDER,
        COUNT(DISTINCT os.USER_ID) USERS
    FROM USER_INFO ui
    JOIN ONLINE_SALE os USING (USER_ID)
    WHERE ui.GENDER = 0
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
    
    UNION ALL
    
    SELECT
        YEAR(SALES_DATE) YEAR,
        MONTH(SALES_DATE) MONTH,
        1 AS GENDER,
        COUNT(DISTINCT os.USER_ID) USERS
    FROM USER_INFO ui
    JOIN ONLINE_SALE os USING (USER_ID)
    WHERE ui.GENDER = 1
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
)
SELECT
    YEAR,
    MONTH,
    GENDER,
    USERS
FROM T1
ORDER BY
    YEAR, MONTH, GENDER;
    