SELECT 
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    GENDER, 
    COUNT(DISTINCT USER_ID) AS USERS
FROM USER_INFO
JOIN ONLINE_SALE USING (USER_ID)
WHERE GENDER IS NOT NULL  -- 성별 정보가 없는 경우 제외 (문제 조건에 따라)
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;