WITH D AS (
    SELECT
        COUNT(*) AS TOTAL_USERS_2021
    FROM USER_INFO
    WHERE USER_INFO.JOINED LIKE '2021%'
),
N AS (
    SELECT
        YEAR(OS.SALES_DATE) AS YEAR,
        MONTH(OS.SALES_DATE) AS MONTH,
        COUNT(DISTINCT OS.USER_ID) AS USER_COUNT
    FROM ONLINE_SALE OS
    JOIN USER_INFO UI USING(USER_ID)
    WHERE UI.JOINED LIKE '2021%'
    GROUP BY YEAR, MONTH
)
SELECT
    N.YEAR AS YEAR,
    N.MONTH AS MONTH,
    N.USER_COUNT AS PURCHASED_USERS,
    ROUND(N.USER_COUNT / D.TOTAL_USERS_2021, 1) AS PUCHASED_RATIO
FROM N
JOIN D
ORDER BY
    YEAR,
    MONTH;