SELECT ID, NAME, HOST_ID
FROM (
    SELECT
        ID, NAME, HOST_ID,
        COUNT(*) OVER (PARTITION BY HOST_ID) AS CNT
    FROM PLACES
) t
WHERE CNT >= 2
ORDER BY ID;


# WHERE  IN (
#     SELECT HOST_ID
#     FROM PLACES
#     GROUP BY HOST_ID
#     HAVING COUNT(ID) > 1
# )