SELECT
    P.PRODUCT_ID, 
    PRODUCT_NAME,
    (P.PRICE * TOTAL_AMOUNT) AS TOTAL_SALES
FROM
    FOOD_PRODUCT P
JOIN (
    SELECT
        PRODUCT_ID,
        SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM
        FOOD_ORDER
    WHERE
        PRODUCE_DATE LIKE '2022-05%'
    GROUP BY
        PRODUCT_ID
) R ON P.PRODUCT_ID = R.PRODUCT_ID 
ORDER BY 
    TOTAL_SALES DESC, P.PRODUCT_ID ASC