WITH RENTAL_HISTORY AS (
    SELECT 
        h.HISTORY_ID, 
        h.CAR_ID,
        c.DAILY_FEE,
        c.CAR_TYPE,
        DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_PERIOD,
        CASE 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE '미적용'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    JOIN CAR_RENTAL_COMPANY_CAR c USING (CAR_ID)
    WHERE c.CAR_TYPE = '트럭'
)
SELECT
    HISTORY_ID,
    FLOOR(h.DAILY_FEE * h.RENTAL_PERIOD * (100 - IFNULL(p.DISCOUNT_RATE, 0)) / 100)  AS FEE
FROM RENTAL_HISTORY h
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p 
    ON h.DURATION_TYPE = p.DURATION_TYPE 
    AND h.CAR_TYPE = p.CAR_TYPE
ORDER BY FEE DESC, h.HISTORY_ID DESC;
