SELECT
    F.FLAVOR
FROM
    FIRST_HALF F
JOIN (
    SELECT
        FLAVOR,
        SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM 
        JULY
    GROUP BY
        FLAVOR
) AS S ON F.FLAVOR = S.FLAVOR
ORDER BY
    (F.TOTAL_ORDER + S.TOTAL_ORDER) DESC
LIMIT 3;