WITH USERS_OVER_SEVENTY AS (
    SELECT
        WRITER_ID AS USER_ID,
        SUM(PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY USER_ID
    HAVING TOTAL_SALES >= 700000
)
SELECT
    USER_ID,
    NICKNAME,
    TOTAL_SALES
FROM USED_GOODS_USER
JOIN USERS_OVER_SEVENTY USING (USER_ID)
ORDER BY TOTAL_SALES;