# WITH MOST_REVIEWER AS (
#     SELECT
#         MEMBER_ID,
#         COUNT(*) AS REVIEW_CNT
#     FROM REST_REVIEW
#     GROUP BY MEMBER_ID
#     ORDER BY REVIEW_CNT DESC
#     LIMIT 1
# )
# SELECT
#     MP.MEMBER_NAME,
#     RR.REVIEW_TEXT,
#     DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d')
# FROM REST_REVIEW RR
# JOIN MEMBER_PROFILE MP USING (MEMBER_ID)
# JOIN MOST_REVIEWER MR USING (MEMBER_ID)
# ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT
WITH MOST_REVIEWER AS (
    SELECT
        MEMBER_ID,
        RANK() OVER (
            ORDER BY
                COUNT(*) DESC
        ) AS RNK
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)
SELECT
    MP.MEMBER_NAME,
    RR.REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d')
FROM REST_REVIEW RR
JOIN MEMBER_PROFILE MP USING (MEMBER_ID)
JOIN MOST_REVIEWER MR USING (MEMBER_ID)
WHERE RNK = 1
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT