SELECT 
    b.CATEGORY, 
    SUM(bs.SALES) AS TOTAL_SALES
FROM 
    BOOK b
JOIN 
    BOOK_SALES bs
    ON bs.BOOK_ID = b.BOOK_ID
WHERE 
    bs.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY 
    b.CATEGORY
ORDER BY 
    b.CATEGORY ASC;